# =================================================VIEW SERVER CONFIG=================================================
server.port=8083

# =================================================SPRING APP CONFIG=================================================
spring.application.name=api-gateway

# =================================================GATEWAY ROUTES=================================================

# 🔓 1. Public Route (Login & Register)
spring.cloud.gateway.routes[0].id=maithil-auth-open
spring.cloud.gateway.routes[0].uri=http://auth-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/login,/auth/admin/login,/auth/register,/auth/refresh,/auth/admin/refresh,/auth/me-open

# 🔐 2. Protected Route (Auth Service - Secure)
spring.cloud.gateway.routes[1].id=maithil-auth-secure
spring.cloud.gateway.routes[1].uri=http://auth-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[1].filters[0].name=JwtAuth

# 🔐 3. Protected Route (User Service)
spring.cloud.gateway.routes[2].id=maithil-user-secure
spring.cloud.gateway.routes[2].uri=http://user-service:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[2].filters[0].name=JwtAuth

# 🔓 4. Public Route (Product Service - No Auth Filter)
spring.cloud.gateway.routes[3].id=maithil-product-open
spring.cloud.gateway.routes[3].uri=http://product-service:8085
spring.cloud.gateway.routes[3].predicates[0]=Path=/product/api/public/**
spring.cloud.gateway.routes[3].order=-1

# 🔐 5. Protected Route (Product Service - Secure with JwtAuth)
spring.cloud.gateway.routes[4].id=maithil-product-secure
spring.cloud.gateway.routes[4].uri=http://product-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/product/api/admin/**
spring.cloud.gateway.routes[4].filters[0].name=JwtAuth

# 🔓 6. Public Route (Cart Service - No Auth Filter)
spring.cloud.gateway.routes[5].id=maithil-cart-open
spring.cloud.gateway.routes[5].uri=http://cart-service:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/cart/api/public/**
spring.cloud.gateway.routes[5].order=-1

# 🔐 7. Protected Route (Cart Service - Secure with JwtAuth)
spring.cloud.gateway.routes[6].id=maithil-cart-secure
spring.cloud.gateway.routes[6].uri=http://cart-service:8086
spring.cloud.gateway.routes[6].predicates[0]=Path=/cart/api/admin/**,/cart/api/**
spring.cloud.gateway.routes[6].filters[0].name=JwtAuth

# 🔓 8. Public Route (Order Service - No Auth Filter)
spring.cloud.gateway.routes[7].id=maithil-order-open
spring.cloud.gateway.routes[7].uri=http://order-service:8087
spring.cloud.gateway.routes[7].predicates[0]=Path=/order/api/public/**
spring.cloud.gateway.routes[7].order=-1

# 🔐 9. Protected Route (Order Service - Secure with JwtAuth)
spring.cloud.gateway.routes[8].id=maithil-order-secure
spring.cloud.gateway.routes[8].uri=http://order-service:8087
spring.cloud.gateway.routes[8].predicates[0]=Path=/order/api/**
spring.cloud.gateway.routes[8].filters[0].name=JwtAuth

# 🔓 10. Public Route (Payment Service - No Auth Filter)
spring.cloud.gateway.routes[9].id=maithil-payment-open
spring.cloud.gateway.routes[9].uri=http://payment-service:8088
spring.cloud.gateway.routes[9].predicates[0]=Path=/payment/api/public/**
spring.cloud.gateway.routes[9].order=-1

# 🔐 11. Protected Route (Payment Service - Secure with JwtAuth)
spring.cloud.gateway.routes[10].id=maithil-payment-secure
spring.cloud.gateway.routes[10].uri=http://payment-service:8088
spring.cloud.gateway.routes[10].predicates[0]=Path=/payment/api/admin/**,/payment/api/**
spring.cloud.gateway.routes[10].filters[0].name=JwtAuth

# =================================================GLOBAL CORS CONFIG=================================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${app.cors.allowed-origins:http://localhost:3000,http://localhost:3001, http://172.27.64.1:3000}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[5]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[6]=HEAD
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# =================================================CUSTOM SECRETS=================================================
jwt.secret=${JWT_SECRET:thisisaverybigsecuritykeywith32bitcharacters-thatwillbeusedinmyapplication.}
gateway.secret=${GATEWAY_SECRET:maithilart-gateway-secret-code-is-rudra}

#Event Driven
maithil.event.enabled=false

#RateLimitter
maithil.rate-limit.max-requests= 100000
maithil.rate-limit.window = 1

# Observability
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
maithil.observability.application=maithil-art
maithil.observability.environment=dev